server:
  port: 8080 #Tomcat端口
spring:
  dubbo:
    application:
      name: dubbo-doc #应用名
    registry:
      address: zookeeper://150.158.153.134 #zookeeper地址
      port: 2181 #提供注册的端口
    protocol:
      name: dubbo
      port: 20890 #dubbo服务暴露的端口
    scan: com.wdg.provider.impl #扫描的包名